### PR TITLE
compatibility shim, file level events in lion, runtime version detection

### PR DESCRIPTION
**Pull request by ttilley**
The title essentially says it. I'd appreciate a look through the diff, if only for code review.

C isn't a language that quite makes me happy per se, so I'm looking forward to cheating and re-implementing fsevent_watch in ObjC with CDEvents. This is the first chunk of functionality I attempted to move over.

There are changes in your ARC branch not necessarily related to ARC that I'm guessing I'd want to include in this version of the project. I'd also like to create initializers that take booleans for enabling flags rather than the raw flags value, but I'm new to ObjC and am unsure quite how to do that without creating way too many initializer variants... Coming from ruby/python the schism between named arguments and selectors is a bit jarring. ;)

### CODE REVIEW

**Comment by ttilley** [comment]
or not?

**Comment by rastersize** [comment]
Hi, sorry for the long delay on my answer (exam time and new courses in school ate my time).

I've look through your code and I would gladly merge your pull request.

I did see one minor "oddity" in the code though, in the test app you use `bool` instead of the Objective-C type `BOOL`. The former is for `true` and `false` while the latter is for `YES` and `NO`, even though they can be used interchangeably at the moment that might change some time in the future so better safe than sorry :). I will go ahead and merge the pull request and change it in my repository since it's such a minor thing.

Regarding the changes in the ARC branch, there aren't that many changes which would be usable in the current master and develop branches. This since most of the stuff used were introduced in the modern Objective-C runtime (i.e. the 64 bit runtime). So I will probably merge the things that can be used in the 32 bit runtime back to the master and develop branches but you are of course more than welcome to merge in as much as you want :)

Also your comment on one of [the commits](https://github.com/rastersize/CDEvents/commit/4bf77e1cabcf87d7b0e73fde2623f7626d847049#commitcomment-542788) have made me change my mind and I will modify the ARC branch to be compatible on 10.6 (as it probably makes more sense even though one will have to zero-out the delegate reference manually).

When it comes the initializer the C way is to use the raw flag value. Though since you dislike it you could probably add an initializer method that takes a dictionary or array with strings representing flags to enable. At least that's the first solution that enters my mind.

With an array:

```
Header:
-------
extern NSString *const kCDEventStreamEventFlagUserDroppedKey;
extern NSString *const ...

     - (id)initWithURLs:(NSArray *)URLs
               delegate:(id<CDEventsDelegate>)delegate
              onRunLoop:(NSRunLoop *)runLoop
   sinceEventIdentifier:(CDEventIdentifier)sinceEventIdentifier
   notificationLantency:(CFTimeInterval)notificationLatency
ignoreEventsFromSubDirs:(BOOL)ignoreEventsFromSubDirs
            excludeURLs:(NSArray *)exludeURLs
streamCreationFlagArray:(NSArrau)streamCreationFlags;


Usage:
------------
[[CDEvents] initWithURLs:... streamCreationFlags:[NSArray arrayWithObjects:kCDEventStreamEventFlagUserDroppedKey, ..., nil]];
```

You get the picture. The strings representing the keys could then matched to their `kFSEvent*` counterpart.

So once again thanks for improving the code and sorry for taking so long to reply :)

**Comment by ttilley** [comment]
Since making this pull request and now I have noticed that file-level event flags get set even when you don't request file-level information... So you could get a directory path back with the flag ItemIsFile set. This is a bit confusing to say the least and I have an open ticket with apple trying to get more information...

Thanks for the feedback. :)

**Comment by rastersize** [comment]
Oh that's a nice little bug. Thanks for sharing!

**Comment by ttilley** [comment]
You may be interested in the response from apple dev support, which you can read here: https://github.com/thibaudgg/rb-fsevent/issues/14#issuecomment-1984710

**Pull request merged**
