### PR TITLE
Casting Warnings in XCode 5

### PR DESCRIPTION
**Pull request by rience**
...lags (Due to Warnings in XCode 5)

This is due to new warnings introduced in XCode 5.

### CODE REVIEW

**Comment by vtourraine** [comment]
I think we should rather change the ivar type, instead of casting it later.

The declaration in `CDEvents.m` should be:

``` objc
CDEventsEventStreamCreationFlags _eventStreamCreationFlags;
```

**Comment by vtourraine** [comment]
As for the cast in `CDEvent.m`, I think we should use:

``` objc
[[aDecoder decodeObjectForKey:@"flags"] unsignedIntValue]
```

(note the `unsignedIntValue` instead of the `unsignedIntegerValue`)

I’d be happy to send a PR, but since this one already addresses this specific issue, I guess you could just update to code then merge it. Thanks!

**Comment by rastersize** [comment]
Hi there! First of all sorry for taking so long to before having a look at this pull!

I agree with @vtourraine that the ivar’s declaration should be changed instead of casting the value. As well using `unsignedIntValue` in `CDEvent.m`.

I’m open to any way of getting that change in. Either if you, @rience, want to update this pull or if @vtourraine creates a new pull request.

**Comment by rience** [comment]
@vtourraine all your suggestions make much more sense. I've updated my commit. @rastersize - I think you can go ahead and merge this. Thanks !

**Comment by rastersize** [comment]
Thank you guys!

**Comment by vtourraine** [comment]
Awesome! Glad it's been helpful. 

If you add a tag for these changes, I'd be happy to push it to CocoaPods too.

**Comment by Bhushan30** [comment]
Thank you for guidance…

**Comment by i386** [comment]
Funny I just fixed these warnings on a local pod myself and was about to create a pull request. Looking forward to getting rid of these warnings soon :+1:

**Comment by rastersize** [comment]
@vtourraine I’ve pushed version/tag 1.2.2 now so if you want to push it to CocoaPods that would be awesome!

**Comment by vtourraine** [comment]
There you go, the `1.2.2` is now available on CocoaPods.

**Pull request merged**
